geo_datasets:
  - GSE37946
  - GSE42822
  - GSE44272
  - GSE50948
  - GSE58984
  - GSE66305
  - GSE70233
  - GSE76360
genes:
  - ERBB2
  - PHLDA1
  - PHLDA2
  - PHLDA3
packages:
  - dplyr
  - GEOquery
  - ggplot2
  - jetset
  - magrittr
  - memoise
  - rentrez
  - rvest
  - simpleCache
  - yaml
# vi: set ts=2 sts=2 sw=2 :
