---
output: html_notebook
title: "Datasets Information"
---
```{r}
source(rprojroot::is_git_root$find_file('lib/R/utils.R'))
config <- notebook_setup('dplyr', 'ggplot2')
```

## Experimental design
```{r}
read.delim('annot/datasets.tsv', na.strings='')
```
```{r}
# exclude "brief exposure" dataset
geo_datasets <- setdiff(config$geo_datasets, 'GSE76360')

dat <- list()
for (gse_id in geo_datasets) try(silent=T, {
    dat[[gse_id]] <- gse_id %>%
        parse_annotation() %>%
        select(her2, treatment, outcome) %>%
        cbind(data.frame(gse_id=gse_id))
})
dat <- dat %>%
    do.call(what=rbind) %>%
    filter(her2 == 'HER2+' & !is.na(treatment) & !is.na(outcome)) %>%
    mutate(group=factor(paste(treatment, outcome, sep='/')))

sample_plot <- ggplot(dat, aes(gse_id, fill=group)) +
    geom_bar(position='dodge') +
    scale_fill_brewer(palette='Paired', direction=-1)
print(sample_plot)
```
## Choose dataset
```{r}
config$geo_datasets %>% paste(seq_along(.), ., sep=': ') %>% cat(sep=', ')
```
```{r}
gse_id <- config$geo_datasets[8]
cat('Selected dataset:', gse_id)
```

## Description
Information retrieved from NCBI database, GEO website and `GEOmetadb`.
```{r}
gse_id %>%
    sprintf(fmt='output/info/%s.txt') %>%
    dget() %>%
    extract(c('title', 'summary', 'Overall design', 'geo_url', 'article_url', 'article_title', 'article_abstract')) %>%
    lapply(paste, collapse=' ') %>%
    paste(toupper(names(.)), ., sep=': ') %>%
    stringr::str_wrap(width=90) %>%
    cat(sep='\n\n')
```

## Article highlights
Relevant excerpts from associated publication.
```{r}
gse_id %>%
    sprintf(fmt='annot/article/%s.txt') %>%
    scan(character(), sep='\n', quote='"', comment.char='(', quiet=T) %>%
    stringr::str_wrap(width=90) %>%
    cat(sep='\n\n')
```
