---
output: html_notebook
title: "Exploratory Analysis"
---
```{r}
source(rprojroot::is_git_root$find_file('lib/R/utils.R'))
config <- setup(packages=c('dplyr', 'GEOquery', 'ggplot2', 'jetset', 'tibble'))

platform_map <- c(GPL96='hgu133a', GPL570='hgu133plus2')
```

## Choose dataset
```{r}
config$geo_datasets %>% paste(seq_along(.), ., sep=': ') %>% cat(sep=', ')
```
```{r}
gse_id <- config$geo_datasets[1]

cat('Selected dataset:', gse_id)
```

# Load data
```{r}
eset <- load_data(gse_id)
platform <- platform_map[attr(eset, 'annotation')]

eset
```
```{r}
annot <- parse_annotation(gse_id)

annot %>%
    filter(her2 == 'HER2+') %>%
    select(treatment, outcome) %>%
    table()
```
```{r}
probes <- jmap(platform, symbol=config$genes)

annot <- annot %>%
    filter(her2 == 'HER2+' & treatment != 'none' & !is.na(outcome))

dat <- eset %>%
    exprs() %>%
    extract(probes, annot$geo_accession) %>%
    t() %>%
    as.data.frame() %>%
    setNames(config$genes) %>%
    cbind(select(annot, geo_accession, treatment, outcome))

dat
```

# Expression levels
```{r}
plot_expr <- function(gene, dat) {
    p_value <- with(dat, {
        x <- dat[outcome == 'pCR', gene]
        y <- dat[outcome == 'RD', gene]
        t.test(x, y)$p.value
    })
    ggplot(dat) +
        geom_boxplot() +
        geom_jitter(position=position_jitter(width=0.1)) +
        aes_string(x='outcome', y=gene, fill='outcome') +
        ggtitle(gene, subtitle=sprintf("P-value for t-test: %.3f", p_value))
}

for (gene in config$genes) {
    print(plot_expr(gene, dat))
}
```

## Correlation between genes
```{r}
plot_corr <- function(pair, dat) {
    ggplot(dat) + geom_point() +
        aes_string(pair[1], pair[2], color='outcome') +
        ggtitle(paste(pair[1], "vs", pair[2]),
                subtitle=sprintf('Correlation: %.2f', cor(dat[[pair[1]]], dat[[pair[2]]])))
}

gene_pairs <- combn(config$genes, 2, simplify=FALSE)

for (pair in gene_pairs) {
    print(plot_corr(pair, dat))
}
```

# Correlation
```{r}
probes <- platform %>%
    sprintf(fmt='scores.%s') %>%
    get %>%
    rownames_to_column %>%
    filter(!duplicated(EntrezID)) %$%
    rowname

```
